// boot.js — o2switch / Passenger startup wrapper.
//
// Loads environment variables from a `.env` file placed at the application root
// BEFORE starting the Next.js standalone server. This keeps server-side secrets
// (Supabase service-role key, Stripe keys, CJ credentials, CRON secret, …)
// working even if the o2switch "Setup Node.js App" panel loses its environment
// variables (which it has repeatedly done on redeploy/restart).
//
// - Zero dependencies (no dotenv needed).
// - Panel / Passenger variables always WIN: we only set a key that is not
//   already present in process.env, so an env var configured in o2switch still
//   takes precedence over the file.
// - The `.env` file is NEVER shipped in the deploy package, so redeploying does
//   not overwrite or delete your secrets.
//
// To use: set the app's "Application startup file" to `boot.js` (instead of
// `server.js`) in the o2switch Node.js panel, and create a `.env` file next to
// this one at the application root.
const fs = require("fs");
const path = require("path");

try {
  const envPath = path.join(__dirname, ".env");
  const raw = fs.readFileSync(envPath, "utf8");
  let loaded = 0;
  for (let line of raw.split(/\r?\n/)) {
    line = line.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("export ")) line = line.slice(7).trim();
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    // Strip a single pair of surrounding quotes, if present.
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (key && !(key in process.env)) {
      process.env[key] = val;
      loaded++;
    }
  }
  console.log(`[boot] Loaded ${loaded} variable(s) from .env`);
} catch (e) {
  if (e && e.code === "ENOENT") {
    console.warn("[boot] No .env file found at app root — relying on host env vars only.");
  } else {
    console.error("[boot] .env load error:", e && e.message);
  }
}

// Start the actual Next.js standalone server (unchanged, generated by the build).
require("./server.js");
